import { Room, Booking, User, TimeSlot } from '../types';

export const MOCK_USER: User = {
  id: 'u001',
  mssv: '21IT001',
  name: 'Nguyễn Văn An',
  email: '21it001@vku.udn.vn',
  avatar: null,
  faculty: 'Công nghệ thông tin',
  class: 'CNTT21A',
};

export const MOCK_ROOMS: Room[] = [
  // ─── Tòa A ──────────────────────────────────────────────
  {
    id: 'A101',
    name: 'Phòng A101',
    building: 'Tòa A',
    floor: 1,
    capacity: 40,
    type: 'classroom',
    amenities: ['Máy chiếu', 'Bảng trắng', 'Điều hòa', 'WiFi'],
    status: 'available',
    image: null,
    description: 'Phòng học lý thuyết tầng 1 tòa A, trang bị đầy đủ máy chiếu và điều hòa.',
  },
  {
    id: 'A102',
    name: 'Phòng Thảo luận A102',
    building: 'Tòa A',
    floor: 1,
    capacity: 8,
    type: 'seminar',
    amenities: ['Bảng trắng', 'Máy chiếu', 'Điều hòa'],
    status: 'occupied',
    image: null,
    description: 'Phòng thảo luận nhóm nhỏ, sức chứa 8 sinh viên.',
  },
  {
    id: 'A103',
    name: 'Phòng Học nhóm A103',
    building: 'Tòa A',
    floor: 1,
    capacity: 4,
    type: 'seminar',
    amenities: ['Bảng trắng', 'Điều hòa'],
    status: 'available',
    image: null,
    description: 'Phòng học nhóm riêng tư dành cho 4 sinh viên.',
  },
  {
    id: 'A201',
    name: 'Phòng A201',
    building: 'Tòa A',
    floor: 2,
    capacity: 35,
    type: 'classroom',
    amenities: ['Máy chiếu', 'Bảng trắng', 'Điều hòa', 'Micro'],
    status: 'available',
    image: null,
    description: 'Phòng học chuẩn tầng 2 tòa A.',
  },
  {
    id: 'SEM01',
    name: 'Seminar A301',
    building: 'Tòa A',
    floor: 3,
    capacity: 18,
    type: 'seminar',
    amenities: ['Máy chiếu', 'Bảng trắng', 'Điều hòa', 'Webcam'],
    status: 'available',
    image: null,
    description: 'Phòng hội thảo chuyên đề khoa CNTT, tối đa 18 chỗ.',
  },

  // ─── Tòa B ──────────────────────────────────────────────
  {
    id: 'B101',
    name: 'Phòng B101',
    building: 'Tòa B',
    floor: 1,
    capacity: 30,
    type: 'classroom',
    amenities: ['Máy chiếu', 'Bảng trắng', 'Điều hòa', 'WiFi'],
    status: 'occupied',
    image: null,
    description: 'Phòng học tầng 1 tòa B.',
  },
  {
    id: 'B102',
    name: 'Phòng Seminar B102',
    building: 'Tòa B',
    floor: 1,
    capacity: 12,
    type: 'seminar',
    amenities: ['Máy chiếu', 'Bảng trắng', 'Điều hòa'],
    status: 'available',
    image: null,
    description: 'Phòng seminar nhóm 12 người trang bị bảng tương tác.',
  },
  {
    id: 'B201',
    name: 'Hội trường B201',
    building: 'Tòa B',
    floor: 2,
    capacity: 50,
    type: 'classroom',
    amenities: ['Máy chiếu', 'Bảng trắng', 'Điều hòa', 'Micro', 'Loa'],
    status: 'available',
    image: null,
    description: 'Hội trường sinh hoạt chuyên đề tầng 2 tòa B.',
  },
  {
    id: 'SEM02',
    name: 'Phòng Thảo luận B301',
    building: 'Tòa B',
    floor: 3,
    capacity: 6,
    type: 'seminar',
    amenities: ['Bảng trắng', 'Điều hòa'],
    status: 'available',
    image: null,
    description: 'Phòng thảo luận nhóm nhỏ 6 sinh viên, yên tĩnh.',
  },

  // ─── Tòa C ──────────────────────────────────────────────
  {
    id: 'LAB01',
    name: 'Lab Máy tính C101',
    building: 'Tòa C',
    floor: 1,
    capacity: 20,
    type: 'lab',
    amenities: ['PC cấu hình cao', 'Máy chiếu', 'Điều hòa', 'Bảng trắng'],
    status: 'available',
    image: null,
    description: 'Phòng thực hành máy tính 20 PC cấu hình cao cho môn Lập trình.',
  },
  {
    id: 'LAB02',
    name: 'Lab Mạng C102',
    building: 'Tòa C',
    floor: 1,
    capacity: 16,
    type: 'lab',
    amenities: ['PC cấu hình cao', 'Máy chiếu', 'Điều hòa', 'Bảng trắng'],
    status: 'occupied',
    image: null,
    description: 'Phòng thực hành mạng máy tính và an toàn thông tin.',
  },
  {
    id: 'LAB03',
    name: 'Lab Đồ họa C201',
    building: 'Tòa C',
    floor: 2,
    capacity: 14,
    type: 'lab',
    amenities: ['PC cấu hình cao', 'Máy chiếu', 'Điều hòa'],
    status: 'available',
    image: null,
    description: 'Phòng thực hành thiết kế đồ họa & đa phương tiện.',
  },
  {
    id: 'LAB04',
    name: 'Lab AI & IoT C202',
    building: 'Tòa C',
    floor: 2,
    capacity: 10,
    type: 'lab',
    amenities: ['PC cấu hình cao', 'Máy chiếu', 'Điều hòa', 'Bảng trắng'],
    status: 'available',
    image: null,
    description: 'Phòng lab nghiên cứu AI & IoT trang bị card GPU mạnh mẽ.',
  },

  // ─── Tòa V ──────────────────────────────────────────────
  {
    id: 'V101',
    name: 'Phòng Nghiên cứu V101',
    building: 'Tòa V',
    floor: 1,
    capacity: 6,
    type: 'seminar',
    amenities: ['Máy chiếu', 'Bảng trắng', 'Điều hòa', 'PC cấu hình cao'],
    status: 'available',
    image: null,
    description: 'Phòng nghiên cứu sinh viên sáng tạo tại Tòa V, đầy đủ PC cấu hình cao.',
  },
  {
    id: 'V102',
    name: 'Phòng Thảo luận V102',
    building: 'Tòa V',
    floor: 1,
    capacity: 4,
    type: 'seminar',
    amenities: ['Bảng trắng', 'Điều hòa', 'WiFi'],
    status: 'available',
    image: null,
    description: 'Không gian họp nhóm 4 người cho dự án khởi nghiệp sinh viên.',
  },
  {
    id: 'V201',
    name: 'Lab Innovation V201',
    building: 'Tòa V',
    floor: 2,
    capacity: 15,
    type: 'lab',
    amenities: ['PC cấu hình cao', 'Máy chiếu', 'Bảng trắng', 'Điều hòa'],
    status: 'occupied',
    image: null,
    description: 'Lab sáng tạo đổi mới công nghệ Tòa V với 15 dàn PC cấu hình cao.',
  },
  {
    id: 'V202',
    name: 'Studio Đa phương tiện V202',
    building: 'Tòa V',
    floor: 2,
    capacity: 8,
    type: 'lab',
    amenities: ['PC cấu hình cao', 'Điều hòa', 'Máy chiếu'],
    status: 'available',
    image: null,
    description: 'Studio sản xuất nội dung số và kiểm thử ứng dụng di động.',
  },
  {
    id: 'V301',
    name: 'Phòng Khởi nghiệp V301',
    building: 'Tòa V',
    floor: 3,
    capacity: 20,
    type: 'seminar',
    amenities: ['Máy chiếu', 'Bảng trắng', 'Điều hòa', 'PC cấu hình cao'],
    status: 'available',
    image: null,
    description: 'Không gian ươm mầm doanh nghiệp sinh viên VKU, tối đa 20 người.',
  },
  {
    id: 'V302',
    name: 'Phòng Phỏng vấn V302',
    building: 'Tòa V',
    floor: 3,
    capacity: 2,
    type: 'seminar',
    amenities: ['Bảng trắng', 'Điều hòa'],
    status: 'available',
    image: null,
    description: 'Phòng phỏng vấn tuyển dụng & trao đổi 1-1 cho sinh viên.',
  },
];

const today = new Date();
const fmt = (d: Date) => d.toISOString().split('T')[0];
const addDays = (d: Date, n: number) => {
  const nd = new Date(d);
  nd.setDate(nd.getDate() + n);
  return nd;
};

export const TIME_SLOTS: TimeSlot[] = [
  { id: 'slot-1', label: '07:30 – 09:30', start: '07:30', end: '09:30' },
  { id: 'slot-2', label: '09:30 – 11:30', start: '09:30', end: '11:30' },
  { id: 'slot-3', label: '13:00 – 15:00', start: '13:00', end: '15:00' },
  { id: 'slot-4', label: '15:00 – 17:00', start: '15:00', end: '17:00' },
  { id: 'slot-5', label: '17:30 – 19:30', start: '17:30', end: '19:30' },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk001',
    userId: 'u001',
    roomId: 'A101',
    roomName: 'Phòng A101',
    date: fmt(addDays(today, 1)),
    startTime: '07:30',
    endTime: '09:30',
    purpose: 'Học nhóm môn Trí tuệ nhân tạo',
    status: 'confirmed',
    createdAt: new Date().toISOString(),
    synced: true,
    passCode: 'VKU-PASS-A101-7291',
  },
  {
    id: 'bk002',
    userId: 'u001',
    roomId: 'V101',
    roomName: 'Phòng Nghiên cứu V101',
    date: fmt(addDays(today, 2)),
    startTime: '13:00',
    endTime: '15:00',
    purpose: 'Thực hành lập trình React Native',
    status: 'confirmed',
    createdAt: new Date().toISOString(),
    synced: true,
    passCode: 'VKU-PASS-V101-4820',
  },
  {
    id: 'bk003',
    userId: 'u001',
    roomId: 'LAB01',
    roomName: 'Lab Máy tính C101',
    date: fmt(addDays(today, -2)),
    startTime: '09:30',
    endTime: '11:30',
    purpose: 'Họp nhóm đồ án tốt nghiệp',
    status: 'completed',
    createdAt: new Date().toISOString(),
    synced: true,
    passCode: 'VKU-PASS-C101-1934',
  },
  {
    id: 'bk004',
    userId: 'u001',
    roomId: 'B201',
    roomName: 'Hội trường B201',
    date: fmt(addDays(today, -4)),
    startTime: '13:00',
    endTime: '15:00',
    purpose: 'Thuyết trình môn PTTKHT',
    status: 'completed',
    createdAt: new Date().toISOString(),
    synced: true,
    passCode: 'VKU-PASS-B201-5502',
  },
  {
    id: 'bk005',
    userId: 'u001',
    roomId: 'LAB02',
    roomName: 'Lab Mạng C102',
    date: fmt(addDays(today, -1)),
    startTime: '07:30',
    endTime: '09:30',
    purpose: 'Thực hành mạng máy tính',
    status: 'cancelled',
    createdAt: new Date().toISOString(),
    synced: true,
    passCode: 'VKU-PASS-C102-6188',
  },
];
